#:schema node_modules/wrangler/config-schema.json
name = "api"
main = "src/main.ts"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat_populate_process_env"]
workers_dev = false
preview_urls = false

[env.local.vars]
ALLOW_ORIGIN = "http://localhost:3000"
APP_URL = "http://localhost:8787"
ENVIRONMENT = "local"
HATENA_API_URL = "https://blog.hatena.ne.jp"
HATENA_BASE_URL = "https://hrkmtsmt.hatenablog.com"
HATENA_OAUTH_URL = "https://www.hatena.com"
QIITA_API_URL = "https://qiita.com/api/v2"
QIITA_BASE_URL = "https://qiita.com"
SIZU_API_URL = "https://sizu.me/api/v1"
SIZU_BASE_URL = "https://sizu.me"
ZENN_API_URL = "https://zenn.dev/api"
ZENN_BASE_URL = "https://zenn.dev"

[env.production]
name = "api"
[env.production.vars]
ALLOW_ORIGIN = "https://hrkmtsmt.me"
APP_URL = "https://api.hrkmtsmt.me"
ENVIRONMENT = "production"
HATENA_API_URL = "https://blog.hatena.ne.jp"
HATENA_BASE_URL = "https://hrkmtsmt.hatenablog.com"
HATENA_OAUTH_URL = "https://www.hatena.com"
QIITA_API_URL = "https://qiita.com/api/v2"
QIITA_BASE_URL = "https://qiita.com"
SIZU_API_URL = "https://sizu.me/api/v1"
SIZU_BASE_URL = "https://sizu.me"
ZENN_API_URL = "https://zenn.dev/api"
ZENN_BASE_URL = "https://zenn.dev"

[triggers]
crons = ["0 0 * * mon"]

[observability.logs]
enabled = true

[[env.local.d1_databases]]
binding = "DB"                # i.e. available in your Worker on env.DB
database_name = "local"
database_id = "local"
migrations_dir = "migrations"

[[env.production.d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "hrkmtsmt"
database_id = "51791b72-d7cb-442e-827e-2b7f69919939"
migrations_dir = "migrations"
